# Blacks / Whites / Grays
black: '#000000'
white: '#ffffff'
gray_lighter: '#e9e9e9'
gray_light: '#adadad'
gray_dark: '#4f4f4f'
gray-darker: '#2a2a2a'

#Primary Colors
primary_color: '#5b2e8b'
primary_tint: '#e7dbf3'
primary_shade: '#401363'

# Secondary Colors
secondary_color: '#235b9c'
secondary_tint: '#dde9f6'
secondary_shade: '#0b1257'

# Neutral Colors
neutral_color: '#0c889f'
neutral_tint: '#cceaef'
neutral_shade: '#005d6f'

# Breakout Colors
breakout_color: '#119b4b'
breakout_tint: '#c8e7d5'
breakout_shade: '#005323'

# Accent Colors
accent_color: '#ce694b'
accent_tint: '#ead5ce'
accent_shade: '#a43513'

# Background Colors
bg_color_1: '#fdf8f8'
bg_color_2: '#f1f5fa'

#Fonts
primary_font: sans-serif
secondary_font: sans-serif
tertiary_font: sans-serif

# Connect Background color
background_gradient_color: '#fffac8'

# Add link to a external font for importing
font_source: 'https://use.typekit.net/qdb6iwq.css'
font_name: 'proxima-nova'

#Site Info
site_full_name: 'Maryland State Bar Association'
site_abbreviation: 'MSBA'
site_abbreviation_lower: 'msba'
site_url: 'https://www.msba.org'
site_address_1: 'Street Address'
site_address_2: 'Apt or Unit #'
site_city: 'City or Town'
site_state: 'State'
site_zip: 'Zipcode'
site_phone_1: ''
site_phone_2: ''
laruta_environment:
  default: demo
  type: enum
  choices:
    - 'localhost:9292'
    - '.laruta.io'
    - '.demo.laruta.io'
    - '.org'
laruta_landing_url: 'connect'
laruta_how_to_use_url: 'how-to-use-connect'
laruta_copyright_url: '/copyright'
laruta_privacy_policy_url: '/privacy-policy'
laruta_site_logo: 'https://www.msba.org/content/uploads/sites/7/2018/04/MSBA-2X-Brand-Logo-Dark-Background1.png'


