# Blacks / Whites / Grays
black: '#000000'
white: '#ffffff'
gray-lighter: '#e9e9e9'
gray-light: '#adadad'
gray-dark: '#4f4f4f'
gray-darker: '#2a2a2a'

#Primary Colors
primary-color: '#5b2e8b'
primary-tint: '#e7dbf3'
primary-shade: '#401363'

# Secondary Colors
secondary-color: '#235b9c'
secondary-tint: '#dde9f6'
secondary-shade: '#0b1257'

# Neutral Colors
neutral-color: '#0c889f'
neutral-tint: '#cceaef'
neutral-shade: '#005d6f'

# Breakout Colors
breakout-color: '#119b4b'
breakout-tint: '#c8e7d5'
breakout-shade: '#005323'

# Accent Colors
accent-color: '#ce694b'
accent-tint: '#ead5ce'
accent-shade: '#a43513'

# Background Colors
bg-color-1: '#fdf8f8'
bg-color-2: '#f1f5fa'

#Fonts
primary-font: sans-serif
secondary-font: sans-serif
tertiary-font: sans-serif

# Connect Background color
background-gradient-color: '#fffac8'

# Add link to a external font for importing
font-source: false

#Site Info
site-full-name: 'Maryland State Bar Association'
site-abbreviation: 'MSBA'
site-url: 'https://www.msba.org'
laruta-environment:
  default: demo
  type: enum
  choices:
    - local
    - staging
    - demo
    - production
laruta-landing-url: 'connect'
laruta-how-to-use-url: 'how-to-use-connect'


