# Blacks / Whites / Grays
black:
  type: string
  default: '#000000'

white:
  type: string
  default: '#ffffff'
  
gray-lighter: '#e9e9e9'
gray-light: '#adadad'
gray-dark: '#4f4f4f'
gray-darker: '#2a2a2a'

#Primary Colors
primary-color: '#5b2e8b'
primary-tint: '#e7dbf3'
primary-shade: '#401363'

# Secondary Colors
secondary-color: '#235b9c'
secondary-tint: '#dde9f6'
secondary-shade: '#0b1257'

# Neutral Colors
neutral-color: '#0c889f'
neutral-tint: '#cceaef'
neutral-shade: '#005d6f'

# Breakout Colors
breakout-color: '#119b4b'
breakout-tint: '#c8e7d5'
breakout-shade: '#005323'

# Accent Colors
accent-color: '#ce694b'
accent-tint: '#ead5ce'
accent-shade: '#a43513'

# Background Colors
bg-color-1: '#fdf8f8'
bg-color-2: '#f1f5fa'

#Fonts
primary-font: sans-serif
secondary-font: sans-serif
tertiary-font: sans-serif
